capture_index:
    path:     /
    defaults: { _controller: "LicoboxBundle:Capture:index" }
    methods:  GET

capture_show:
    path:     /{id}/show
    defaults: { _controller: "LicoboxBundle:Capture:show" }
    methods:  GET

capture_new:
    path:     /new
    defaults: { _controller: "LicoboxBundle:Capture:new" }
    methods:  [GET, POST]

capture_edit:
    path:     /{id}/edit
    defaults: { _controller: "LicoboxBundle:Capture:edit" }
    methods:  [GET, POST]

capture_delete:
    path:     /{id}/delete
    defaults: { _controller: "LicoboxBundle:Capture:delete" }
    methods:  DELETE
