user_index:
    path:     /
    defaults: { _controller: "LicoboxBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "LicoboxBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "LicoboxBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "LicoboxBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "LicoboxBundle:User:delete" }
    methods:  DELETE
