LicoboxBundle\Entity\Licorne:
    type: entity
    table: null
    repositoryClass: LicoboxBundle\Repository\LicorneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToOne:
        eyes:
            targetEntity: LicoboxBundle\Entity\Eyes
            inversedBy: licornes
        corne:
            targetEntity: LicoboxBundle\Entity\Corne
            inversedBy: licornes
        pelage:
            targetEntity: LicoboxBundle\Entity\Pelage
            inversedBy: licornes
        habitat:
            targetEntity: LicoboxBundle\Entity\Habitat
            inversedBy: licornes

#
#    manyToMany:
#        eyes:
#          targetEntity: LicoboxBundle\Entity\Eyes

#
#        pelage:
#            targetEntity: Pelage
#            joinColumn:
#                name: id_pelage
#                referencedColumnName: id
#
#        corne:
#            targetEntity: Corne
#            joinColumn:
#                name: id_corne
#                referencedColumnName: id
#    oneToOne:
#        habitat:
#            targetEntity: Habitat
#            jointColumn:
#                name: id_habitat
#                referencedColumnName: id