LicoboxBundle\Entity\Pelage:
    type: entity
    table: null
    repositoryClass: LicoboxBundle\Repository\PelageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255

    oneToMany:
        licornes:
            targetEntity: LicoboxBundle\Entity\Licorne
            mappedBy: pelage

    lifecycleCallbacks: {  }
