<?php

namespace LicoboxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CaptureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaptureRepository extends EntityRepository
{
}
