<?php

namespace LicoboxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EyesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EyesRepository extends EntityRepository
{
}
